name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you're using pnpm, add this step then change the commands and cache key below to use `pnpm`
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Setup tests
        run: |
          git lfs pull
          tar xzf pushup.tar.gz
        working-directory: tests/assets

      - name: Run tests
        run: bun test
